#!/bin/sh

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 pgp.mit.edu < dearmored_key.gpg"
  exit 1
fi

tmp=$(mktemp)

gpg --enarmor | sed 's/ARMORED FILE/PUBLIC KEY BLOCK/' > "$tmp"
curl --data-urlencode "keytext@$tmp" --max-time 60 "http://$1:11371/pks/add"
