#!/bin/sh

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 pgp.mit.edu < key.gpg"
  exit 1
fi

cwd=$(dirname "$0")
tmp=$(mktemp)

cd "$cwd"

./sks-forge-uid/sks-forge-uid -rand > "$tmp"
./sks-upload "$1" < "$tmp"
