#!/bin/sh

keyserver=$1
cwd=$(dirname "$0")
tmp=$(mktemp)

shift
set -e

if [ -z "$keyserver" ]; then
  echo "Usage: $0 pgp.mit.edu [sks-fake-uid flags ...] < dearmored_key.gpg"
  exit 1
fi

cd "$cwd"

./sks-fake-uid/sks-fake-uid "$@" > "$tmp"
./sks-upload "$keyserver" < "$tmp"
